### ISSUE TITLE
Out of memory : Java Heap Space / Engine timeout

### ISSUE THREAD

**Issue by eproulx-petalmd** [sleekbyte/codeclimate-tailor#2]
Hello,

We're experiencing problem with the engine. In our case, it always turns out to a 
> Out of Memory Exception

I modified the engine locally to add some heap space before starting Tailor. I only added these 2 java options
> -Xms1024m -Xmx2048m

Now, the heap space problem seems to be resolved but I'm experiencing the CC::Analyzer::Engine::EngineTimeout

Here's the code to start analyzing
`docker run   --interactive --tty --rm   --env CODECLIMATE_CODE="$PWD"   --env ENGINE_MEMORY_LIMIT_BYTES="4096000000"   --volume "$PWD":/code   --volume /var/run/docker.sock:/var/run/docker.sock   --volume /tmp/cc:/tmp/cc   codeclimate/codeclimate analyze --dev`

Here's my .codeclimate file with running with the local engine
```
engines:
  tailor-eric:
    enabled: true
    exclude_paths:
    - DerivedData/**/*
    - petalmd/Automation\ Tests/**/*
    - petalmd/Supporting\ Files/**/*
    - PetalMD\ Integration\ Tests/**/*
    - PetalMD\ Unit\ Tests/**/*
    - PetalMD\ UI\ Tests/**/*
    - PetalMD\ Frameworks/**/*
    - petalmd/Images.xcassets/**/*
    - petalmd/Base.Iproj/**/*
    - petalmd/Frameworks/**/*
    - PetalMD.xcodeproj/**/*
    - PetalMD.xcworkspace/**/*
    - Pods/**/*
    - config/**/*
    - fastlane/**/*
    - features/**/*
    - "**.xib"
    - "**.storyboard"
    - "**.lock"
    - "**.ipa"
    - "**.rb"
    - "**.entitlements"
    - "**.strings"
    - "**.plist"
    - "Gemfile"
    - "Podfile"
ratings:
  paths:
  - "**.swift"
```
